language: ruby
sudo: false
cache: bundler
addons:
  postgresql: "9.3"
before_script:
  - npm install --silent
  - cp config/application.sample.yml config/application.yml
  - psql -c 'create database rails_assets_test;' -U postgres
  - bundle exec rake db:schema:load
  - export DISPLAY=:99.0
  - bower --version
  - sh -e /etc/init.d/xvfb start
script: bundle exec rspec
services:
  - redis-server
rvm:
  - 2.2.3
  - 2.3.0
