language: ruby 
sudo: false
bundler_args: --without development
before_script:
  - npm install --silent
  - cp config/application.sample.yml config/application.yml
  - cp config/database.sample.yml config/database.yml
  - psql -c 'create database rails_assets_test;' -U postgres
  - bundle exec rake db:migrate
script: bundle exec rspec
services:
  - redis-server
rvm:
  - 2.2.3
